# Device Basic Configuration
esphome:
  name: irrigazione
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
# Optional manual IP
#    manual_ip:
#    static_ip: 192.168.1.11
#    gateway: 192.168.1.1
#    subnet: 255.255.255.0  

# Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Irrigazione Fallback Hotspot"
    password: !secret ap_password

captive_portal:

# Enable logging
logger:

web_server:
  port: 80

# Enable Home Assistant API
api:
  password: !secret api_password
  
  services:
    - service: set_multiplier
      variables:
        multiplier: float
      then:
        - sprinkler.set_multiplier:
            id: irrigazione
            multiplier: !lambda 'return multiplier;'
    - service: start_full_cycle
      then:
        - sprinkler.start_full_cycle: irrigazione
    - service: start_single_valve
      variables:
        valve: int
      then:
        - sprinkler.start_single_valve:
            id: irrigazione
            valve_number: !lambda 'return valve;'
    - service: next_valve
      then:
        - sprinkler.next_valve: irrigazione
    - service: previous_valve
      then:
        - sprinkler.previous_valve: irrigazione
    - service: shutdown
      then:
        - sprinkler.shutdown: irrigazione
 
ota:
  password: !secret ota_password

# Device Specific Configuration
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: 
        input: true
        pullup: true  
      inverted: true
    on_press:
      then:
      - switch.toggle: zona_1
      - switch.turn_off: zona_2 
      - switch.turn_off: zona_3
      - switch.turn_off: zona_4
    name: "pulsante zona 1"
    
  - platform: gpio
    pin:
      number: GPIO9
      mode: 
        input: true
        pullup: true
      inverted: true
    on_press:
      then:
      - switch.toggle: zona_2
      - switch.turn_off: zona_1 
      - switch.turn_off: zona_3
      - switch.turn_off: zona_4  
    name: "pulsante zona 2"
    
  - platform: gpio
    pin:
      number: GPIO10
      mode:
        input: true
        pullup: true
      inverted: true
    on_press:
      then:
      - switch.toggle: zona_3
      - switch.turn_off: zona_1 
      - switch.turn_off: zona_2
      - switch.turn_off: zona_4  
    name: "pulsante zona 3"
    
  - platform: gpio
    pin:
      number: GPIO14
      mode:
        input: true
        pullup: true
      inverted: true
    on_press:
      then:
      - switch.toggle: zona_4
      - switch.turn_off: zona_1 
      - switch.turn_off: zona_2
      - switch.turn_off: zona_3  
    name: "pulsante zona 4"
    
  - platform: status
    name: "stato Sonoff irrigazione"

sprinkler:
  - id: irrigazione
    main_switch: "irrigazione"
    auto_advance_switch: "irrigazione in sequenza"
    #valve_open_delay: 1s # apre la valvola x secondi dopo che si è chiusa la precedente
    valves:
      - valve_switch: "zona 1"
        enable_switch: "abilita zona 1"
        # pump_switch_id: psr
        run_duration: 60s
        valve_switch_id: zona_1
      - valve_switch: "zona 2"
        enable_switch: "abilita zona 2"
        # pump_switch_id: psr
        run_duration: 60s
        valve_switch_id: zona_2
      - valve_switch: "zona 3"
        enable_switch: "abilita zona 3"
        # pump_switch_id: psr
        run_duration: 60s
        valve_switch_id: zona_3
      - valve_switch: "zona 4"
        enable_switch: "abilita zona 4"
        # pump_switch_id: psr
        run_duration: 60s
        valve_switch_id: zona_4 

switch:

#  - platform: gpio 
#    name: "psr"  # -- switch per relè PSR ---
#    pin: GPIOxx
#    id: psr
#    icon: mdi:water-pump
#    restore_mode: always_off      

  - platform: gpio
    name: "zona 1"
    pin: GPIO12
    id: zona_1
    icon: mdi:sprinkler-variant
    interlock: [zona_2, zona_3, zona_4]
    restore_mode: always_off      
    internal: true
    
  - platform: gpio
    name: "zona 2"
    pin: GPIO5
    id: zona_2
    icon: mdi:sprinkler-variant
    interlock: [zona_1, zona_3, zona_4]
    restore_mode: always_off    
    internal: true
    
  - platform: gpio
    name: "zona 3"
    pin: GPIO4
    id: zona_3
    icon: mdi:sprinkler-variant
    interlock: [zona_1, zona_2, zona_4]
    restore_mode: always_off    
    internal: true
    
  - platform: gpio
    name: "zona 4"
    pin: GPIO15
    id: zona_4
    icon: mdi:sprinkler-variant
    interlock: [zona_1, zona_2, zona_3]
    restore_mode: always_off  
    internal: true
    
  - platform: restart
    name: irrigazione restart

text_sensor:
  - platform: version
    name: irrigazione esphome version
    hide_timestamp: true    

  - platform: wifi_info
    ip_address:
      name: irrigazione ip address
      icon: mdi:ip-network-outline             

status_led:
  pin:
    number: GPIO13
    inverted: True
    
sensor:
  - platform: wifi_signal
    name: "irrigazione segnale wifi" 
    update_interval: 3600s      
