# Device esp8266 Basic Configuration
esphome:
  name: $devicename

esp8266:
  board: $board
  framework:
    version: recommended
  board_flash_mode: dout 
  restore_from_flash: true 

preferences:
  flash_write_interval: 90s

# Enable logging
logger:

# Enable Home Assistant API
api:
#  encryption:
#    key: !secret api_key

ota:
  password: !secret ota_password

binary_sensor:
  - platform: status
    name: "$devicename stato"
  
text_sensor:
  - platform: version
    name: "$devicename esphome version"
    hide_timestamp: true    

switch:
  - platform: restart
    name: "$devicename restart"
    
time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Rome
    servers: 192.168.1.1    