wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: $static_ip
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: 192.168.1.100
    #dns2: 8.8.4.4  

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap: {}
  domain: .local
  reboot_timeout: 30min
  fast_connect: true

captive_portal:

#web_server: #disabled since it need a lot of device memory and can lead problems on 8266
#  port: 80

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "$devicename ip address"
      icon: mdi:ip-network-outline

sensor:
  - platform: wifi_signal
    name: "$devicename segnale WiFi"
    update_interval: 3600s    
